"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

#!/usr/bin/python
# -*- coding: utf-8 -*-

import py2app
import sys
#from distutils.core import setup
from os import getcwd
from pathlib import Path
from setuptools import setup

OPTIONS = {'argv_emulation': True, 
            'iconfile': "image/mail.icns",
            'includes': ['PySimpleGUI', 'selenium','csv','time','itertools','datetime','openpyxl'],
            }

sys.argv.append('py2app')
setup(app=['Mac.py'],
      data_files=[],
      options=(dict(py2app=dict(bdist_base=str(Path(getcwd()).parent)
      + '/build', dist_dir=str(Path(getcwd()).parent) + '/dist'))),
      setup_requires=['py2app'])

