"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Care Wtsapp Sender v2 Mac.py']
DATA_FILES = ["./"]
OPTIONS = {'argv_emulation': True, 
            'iconfile':"mail.icns",
            'includes': ['PySimpleGUI', 'selenium','csv','time','itertools','datetime','pandas',"_sysconfigdata"]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
